# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 00:41
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name=django.contrib.auth.models.User)),
                ('name', models.CharField(blank=True, help_text="Don't write salutation, Just write name", max_length=100)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('institute', models.CharField(max_length=100)),
                ('post', models.CharField(choices=[('Professor', 'Professor'), ('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Emeritus Professor', 'Emeritus Professor'), ('Visiting Professor', 'Visiting Professor'), ('Adjunct Professor', 'Adjunct Professor'), ('Retired Professor', 'Retired Professor')], default='Professor', max_length=30)),
                ('areas_of_interest', models.CharField(max_length=1500)),
                ('upload_cv', models.FileField(blank=True, upload_to='media/')),
                ('skypeId', models.CharField(blank=True, max_length=40, null=True)),
                ('personal_home_page_link', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name=django.contrib.auth.models.User)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('institute', models.CharField(max_length=100)),
                ('areas_of_interest', models.CharField(blank=True, max_length=1500)),
                ('upload_cv', models.FileField(blank=True, upload_to='media/')),
                ('work_highlight', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
